export { default as MovieDetails } from './MovieDetails';
export { default as Footer } from './Footer';
export { default as Header } from './Header';
export { default as Movie } from './Movie';
export { default as MoviePoster } from './MoviePoster';
export { default as MovieResult } from './MovieResult';
export { default as Results } from './Results';
export { default as SearchInput } from './SearchInput';
export { default as SearchResults } from './SearchResults';
